### ISSUE TITLE
catkin_lint not compatible with Python 2 anymore

### ISSUE THREAD

**Issue by rhaschke** [fkie/catkin_lint#113]
Latest PyPi release of catkin_lint is not compatible with Python 2.7 anymore:

```
  Traceback (most recent call last):
    File "/usr/local/bin/catkin_lint", line 52, in <module>
      from catkin_lint.main import main
    File "/usr/local/lib/python2.7/dist-packages/catkin_lint/__init__.py", line 39, in <module>
      from ._version import version as __version__
    File "/usr/local/lib/python2.7/dist-packages/catkin_lint/_version.py", line 10
      version: str
             ^
  SyntaxError: invalid syntax
```

It would be great if a version compatible with Python 2 would still be available via `pip install`.

**Comment by rhaschke** [comment]
Looks like the Python 3 requirement comes from (a new release of) `setuptools-scm`, which generates `_version.py`.
Adding a `python_requires=">=3"` in `setup(...)` [should resolve the issue](https://stackoverflow.com/questions/42238484/prevent-package-from-being-installed-on-old-python-versions).
`industrial_ci` [pinned the version manually](https://github.com/ros-industrial/industrial_ci/pull/888/files) for now.
