### ISSUE TITLE
Python 3 test failure

### ISSUE THREAD

**Issue by jpgr87** [fkie/catkin_lint#37]
I'm getting the following error with catkin_lint-1.4.13 when running tests under python-3.5.3:

```
======================================================================
ERROR: runTest (test.test_all_checks.CatkinInvokationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/python-catkin_lint/catkin_lint-1.4.13/test/test_all_checks.py", line 178, in runTest
    os.environ["ROS_PACKAGE_PATH"] = os.pathsep.join(os.path.join([self.wsdir, "src", self.upstream_ws]))
  File "/usr/lib64/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'

----------------------------------------------------------------------
Ran 57 tests in 0.415s

FAILED (errors=1)
```

**Comment by roehling** [comment]
Thanks! Interestingly, this problem never surfaced in the Travis CI build
